<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * link_collectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class link_collectionRepository extends EntityRepository
{
    
    public function findOneByWhere($link,$title) {
        $query = $this->getEntityManager()->createQuery('SELECT a FROM AppBundle:link_collection a  WHERE a.link = :link and a.title = :title')
            ->setParameter("link", $link)
            ->setParameter("title",  $title)
            ->getResult();
        return $query ;
    }
    
}
