<?php

namespace AppBundle\Repository;

/**
 * tender_detailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tender_detailRepository extends \Doctrine\ORM\EntityRepository
{
}
