<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * tender_detailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tender_detailRepository extends EntityRepository
{
    public function findOneByParentId($parentId) {
        $query = $this->getEntityManager()->createQuery('SELECT a FROM AppBundle:tender_detail a  WHERE a.parentid = :parentid')
            ->setParameter("parentid", $parentId)
            ->getResult();
        return $query ;
    }
    
  
}
